environments:
  test:
pipelines:
  testPython1:
    group: defaultGroup
    materials:
      mygit:
        git: https://github.com/JamiePines/gocd-test-1
        auto_update: false
    stages:
      - defaultStage:
          jobs:
            defaultJob:
              artifacts:
                - build:
                    source: hello_world.txt
              tabs:
                hello-world: hello_world.txt
                  tasks:
                    - exec:
                      run_if: passed
                      command: \Python27\python.exe
                      arguments: hello_world.py
  testPython2:
    group: defaultGroup
    materials:
      testPython1:
        pipeline: testPython1
        stage: defaultStage
      mygit:
        auto_update: false
        git: https://github.com/JamiePines/gocd-test-1
    stages:
      - defaultStage:
          jobs:
            defaultJob:
              tasks:
                - fetch:
                    artifact_origin: gocd
                    source: hello_world.txt
                    pipeline: testPython1
                    stage: defaultStage
                    job: defaultJob
                    run_if: passed
                - exec:
                    command: \Python27\python.exe
                    arguments: read_file_add_modified.py
                    run_if: passed

